### PR TITLE
Updated dnscrypt-proxy to 1.9.5

### PR DESCRIPTION
**Pull request by physkets**

### CODE REVIEW

**Comment by thefallenrat** [comment]
Next time when opening a pull request on artix repo always remember these : 

* Make sure the target of pull request are testing branch, as all packages must go through testing repo before being pushed into stable

* If you were bumping `pkgver` of a package, make sure to also reset `pkgrel` back to  `1` as `pkgrel` are only incremented if there are bugfixes introduced or new features ( see [Arch Wiki/PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD) for details)

* Make sure to keep it one commit per pull request, as buildbot can't build packages from batch commits (as far as I know ) - As you can see here, if I change the target of pull request. All merge commits from `master` branch will be pulled from it. So I have to clean it first before merging it.

But anyway, thank you for this. I will merge this soon

**Comment by physkets** [comment]
@thefallenrat I will keep those things in mind. Thanks! 

I did have only one commit in the pull request. I don't know how that happened.

**Comment by thefallenrat** [comment]
That's because I change its target of this pull request into testing branch, Thus bringing empty merge commits into the table

**Comment by physkets** [comment]
I installed just this package from [galaxy-testing], and can confirm that it works.

**Pull request merged**
