### PR TITLE
Add socklog

### PR DESCRIPTION
**Pull request by konimex**
About socklog:

`socklog` in cooperation with the `runit` package, is a small and secure replacement for syslogd. Although there *is* a runscript of `syslog-ng` in [world], but since `socklog` has a tight runit integration it's preferred over `syslog-ng`. (Most runit runscripts which has syslog dependency checks against `socklog` rather than `syslogd`).

### CODE REVIEW

**Comment by thefallenrat** [comment]
Merged. Thank you!

**Comment by udeved** [comment]
@thefallenrat 

Did you merge as rebased merge?

**Comment by thefallenrat** [comment]
That was a squash merge ....

**Comment by udeved** [comment]
Better do rebasedWe need to be careful and watch merges with new pipeline code.
Default merges in testing will build the previous commit sha.
I made it so that if we get a commit before pull, eg someone pushed before your push, the resulting merge will pass the previous commit to build. ;)

**Comment by thefallenrat** [comment]
Awww nooo :((

Sorry, it won't happen again

**Comment by konimex** [comment]
I don't think we need dependencies on `bash` at all.

The run script is `#!/bin/sh`, which means it's Bourne/POSIX sh compliant, which means if I have `/bin/sh` symlinked to `/usr/bin/zsh` or even `/usr/bin/ksh93` it will still work.

**Comment by udeved** [comment]
No problem, good test cases.
Was only tested with default where I had to pul before push while widget edited a build.
It did build my commit before the pull, just GH notification doesn't show status.

**Comment by thefallenrat** [comment]
> I don't think we need dependencies on bash at all.
> 
> The run script is #!/bin/sh, which means it's Bourne/POSIX sh compliant, which means if I have /bin/sh symlinked to /usr/bin/zsh or even /usr/bin/ksh93 it will still work.

Fair point. bash is now removed in depend array(1d03fba)

**Comment by cromerc** [comment]
I would not be so sure, just because it has #!/bin/sh does not mean it works without bash. The only way to know for sure is to check the script manually for bashisms.

**Pull request merged**
