### PR TITLE
add yaourt to galaxy repo

### PR DESCRIPTION
**Pull request by thefallenrat**
Can I add yaourt to galaxy repo, please? I will help maintaining it...

### CODE REVIEW

**Comment by cromerc** [comment]
There is an issue, the package could not be built because of a missing dependency: package-query
If you want to have yaourt built and in the galaxy repo you also need to package and maintain its dependencies.

Also for the next time you open a pull request, open it on the testing branch and not on the master branch please.

**Comment by thefallenrat** [comment]
> There is an issue, the package could not be built because of a missing dependency: package-query
If you want to have yaourt built and in the galaxy repo you also need to package and maintain its dependencies.

Does this mean that if I add package-query and also maintain it, will you allow it?

> Also for the next time you open a pull request, open it on the testing branch and not on the master branch please.

Oops! sorry my mistake... Won't happen again!

**Comment by cromerc** [comment]
> Does this mean that if I add package-query and also maintain it, will you allow it?

Yes, if you maintain both of them it can be included. Please check your optdepends as well, if the "optdepends" are not in the artix repos, you either need to remove those optdepends from the PKGBUILD or adopt those packages as well.
> Oops! sorry my mistake... Won't happen again!

Don't worry about it, you didn't know. Basically all commits should be done to testing, and then later we merge them with master.

**Comment by thefallenrat** [comment]
```
depends=('pacman>=5.0' 'yajl>=2.0')
```
Reading package-query 's PKGBUILD. It looks like it depends on `yajl`, which is an arch package from extra repo...

https://www.archlinux.org/packages/?sort=&q=yajl&maintainer=&flagged=

Does this mean I should wait for `yajl` to be added in artix repo, or would you like me to maintain it as well??

**Comment by udeved** [comment]
@thefallenrat 

Nope, go ahead, we can handle arch extra, its available via arch repos.
Just add package-query and yaourt.

**Comment by thefallenrat** [comment]
> Nope, go ahead, we can handle arch extra, its available via arch repos.
> Just add package-query and yaourt.

Thanks @udeved ! I will pull a request for package-query soon!

**Pull request merged**
